name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: npm install && npm install -g firebase-tools && npm run build && npm run deploy
        working-directory: src/Krakow.Website
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
